# Generated by Django 5.1 on 2025-12-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
    ]
